### ISSUE TITLE
RFE: Export to Calendar

### ISSUE THREAD

**Issue by nognkantoor** [forrestguice/SolunarPeriods#1]
Could this be modified to export to calendar, the way SunTimes can be exported to calendar?

**Comment by forrestguice** [comment]
Very doable. This feature can be added to next SuntimesCalendars version. I want to isolate calendar permissions there. It means adding a ContentProvider here to facilitate it (so I think may take some time to implement).

**Comment by forrestguice** [comment]
This is basically done. I wasn't sure how to implement it, but after taking a fresh look a few weeks ago, I think its now solved. It just needs to be released; I guess first as an update for SuntimesCalendars (v0.5.0), and then an update to SolunarPeriods (to v0.2.0 I guess since functionality is added, or maybe just a patch release instead (v0.1.1)).

If you run the SolunarPeriods `provider` branch, together with the SuntimesCalendars `solunar` branch, then a checkbox for the "Solunar Calendar" should appear in the list in SuntimesCalendars.

**Comment by forrestguice** [comment]
I've put a release build here; https://github.com/forrestguice/SolunarPeriods/releases

If (or when) this app is mature enough, we can have it packaged by F-Droid instead. I'm in support of this, but don't feel strongly enough to take initiative at the moment.
